[project]
name = "ub_nssd"
version = "0.1.0"
description = "Non-Sound Speech Detection (NSSD) Team for UB Voice."
authors = [{ name = "ok-nick, korliu", email = "nick.libraries@gmail.com, koreyliu1221@gmail.com" }]
dependencies = [
  'numba',
  'numpy',
  'torch',
  'tqdm',
  'more-itertools',
  'tiktoken == 0.3.3',
  'whisper-at == 0.4.0; sys_platform == "Linux"',
]

[tool.pyright]
typeCheckingMode = "off"

[tool.ruff]
fixable = ["ALL"]
select = ["ALL"]

[tool.black]
